### ISSUE TITLE
When i npm run start I run into this:

### ISSUE THREAD

**Issue by stephaniegoldman12** [Snowflake-Labs/sfguide-data-apps-demo#6]
<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x104336260 node::Abort() [/usr/local/bin/node]
 2: 0x1043363e8 node::errors::TryCatchScope::~TryCatchScope() [/usr/local/bin/node]
 3: 0x104484e88 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x104484e1c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x104608534 v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
 6: 0x104607054 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x10461239c v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0x104612430 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x1045e52c4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
10: 0x10491d3c8 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x104c31a4c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
12: 0x108ee0698 
13: 0x104c79cb8 Builtins_PromiseRejectReactionJob [/usr/local/bin/node]
14: 0x104be71d8 Builtins_RunMicrotasks [/usr/local/bin/node]
15: 0x104bc33a4 Builtins_JSRunMicrotasksEntry [/usr/local/bin/node]
16: 0x104594ce4 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
17: 0x104595118 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
18: 0x104595204 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/usr/local/bin/node]
19: 0x1045b7e40 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/usr/local/bin/node]
20: 0x1045b86d4 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/usr/local/bin/node]
21: 0x104282db4 node::InternalCallbackScope::Close() [/usr/local/bin/node]
22: 0x10428348c node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
23: 0x1042984c0 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
24: 0x10433a41c node::fs::FSReqCallback::Reject(v8::Local<v8::Value>) [/usr/local/bin/node]
25: 0x10433abe8 node::fs::FSReqAfterScope::Reject(uv_fs_s*) [/usr/local/bin/node]
26: 0x10433ad10 node::fs::AfterStat(uv_fs_s*) [/usr/local/bin/node]
27: 0x104ba3a5c uv__work_done [/usr/local/bin/node]
28: 0x104ba71f8 uv__async_io [/usr/local/bin/node]
29: 0x104bb8f70 uv__io_poll [/usr/local/bin/node]
30: 0x104ba7688 uv_run [/usr/local/bin/node]
31: 0x104283ccc node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
32: 0x10436f440 node::NodeMainInstance::Run(int*, node::Environment*) [/usr/local/bin/node]
33: 0x10436f10c node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/local/bin/node]
34: 0x104308080 node::Start(int, char**) [/usr/local/bin/node]
35: 0x108b5d0f4 
Abort trap: 6

**Comment by sfc-gh-bculberson** [comment]
the private key is likely not set in config correctly. the private key is the text of the key, not a path
